apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindx-backend
  labels:
    app: mindx-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindx-backend
  template:
    metadata:
      labels:
        app: mindx-backend
    spec:
      containers:
      - name: backend
        image: tienndregistry.azurecr.io/mindx-backend:v1.0.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # OpenID Connect Configuration
        - name: OPENID_ISSUER
          value: "https://id-dev.mindx.edu.vn"
        - name: OPENID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: openid-secrets
              key: client-id
        - name: OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: openid-secrets
              key: client-secret
        - name: OPENID_REDIRECT_URI
          value: "https://tiennd.mindx.edu.vn/auth/callback"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: openid-secrets
              key: session-secret
        - name: FRONTEND_URL
          value: "https://tiennd.mindx.edu.vn"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mindx-backend-service
  labels:
    app: mindx-backend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: mindx-backend
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
