apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  jwt-secret: "change-this-to-a-secure-random-string-in-production"
# Note: In production, use Azure Key Vault or sealed secrets instead of plain text
